name: Release (main)
on:
  push:
    tags: ['v*']  # plain version tags like v0.0.1
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          case "$TAG" in *-*) echo "Dev-style tag; skip"; exit 0;; esac
          gh release create "$TAG" --title "$TAG" --generate-notes
