name: Releases

on:
  push:
    branches: [main, dev]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Identity 
        run: | 
          git config user.name "github-actions[bot]" 
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Tag
        id: vars
        run: |
          set -euo pipefail

          VERSION="$(tr -d '[:space:]' < VERSION)"
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            TAG="v${VERSION}"
          else
            SHORTSHA="$(git rev-parse --short "$GITHUB_SHA")"
            TAG="v${VERSION}-${SHORTSHA}"
          fi

          if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
            echo "Tag $TAG already exists; failing."
            exit 1
          fi

          git tag -a "$TAG" -m "Tag $TAG for ${GITHUB_REF_NAME}"
          git push origin "$TAG"

          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create release (main)
        if: github.ref_name == 'main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.vars.outputs.tag }}" \
            --title "${{ steps.vars.outputs.tag }}" \
            --generate-notes

      - name: Create prerelease (dev)
        if: github.ref_name == 'dev'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.vars.outputs.tag }}" \
            --title "${{ steps.vars.outputs.tag }} (dev)" \
            --prerelease \
            --generate-notes
