name: Tag on push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Create and push tag
      run: |
        TAG="v$(cat VERSION | tr -d '[:space:]')"
        git tag "$TAG"
        git push origin "$TAG"
